### ISSUE TITLE
[doc] typo in the example for `createSlice`

### ISSUE THREAD

**Issue by crusoexia** [reduxjs/redux-starter-kit#100]
In the official [createSlice](https://redux-starter-kit.js.org/api/createslice) documentation, in the example it uses `configureStore`, which suppose to be `createSlice`:

<img width="811" alt="screen shot 2019-01-26 at 3 52 43 pm" src="https://user-images.githubusercontent.com/5928754/51784361-7e4dbe00-2182-11e9-8392-9ce7967c10a4.png">

**Comment by markerikson** [comment]
Fixed by #103 (and #101 ).  Thanks!
