### ISSUE TITLE
Proposal: Class-based reducers for readability

### ISSUE THREAD

**Issue by keenondrums** [reduxjs/redux-starter-kit#107]
What do you think of switching to class-based reducers for readability? Take a look at [ngrx-actions](https://github.com/amcdnl/ngrx-actions).

A reducer could look like this
```js
@Store({ todos: [] })
class ReducerTodo {
  @Action(actionType1)
  addTodo() {
  }

  @Action(actionType2, actionType3)
  removeTodo() {
  }
}
```

It's self-documenting because all methods have names. We still could use a map of reducers to pick from by action type under the hood. It allows us to have several actions triggering the same reducer (notice actionType2, actionType3 for removeTodo), while what we have now forces us to duplicate the code.

What we could have different signatures for immer-based reducers and regular ones so we never accidentally invoke immer. We could add initialState property to have better type checking.

So in my mind the final picture would something close to this
```ts
import { Action, DeepReadonly, ReducerClass } from 'redux-starter-kit'

interface IReducerCatState {
  energy: number
}
class ReducerCat extends ReducerClass<IReducerCatState> {
  // type checked and forced to implement by abstract class ReducerClass
  initialState = {
    energy: 100,
  }

  @Action //action here if reflected by TS
  addEnergy(state: IReducerCatState, action: ActionCatEat) {
    return {
      energy: state.energy + action.payload,
    }
  }

  // uses immer
  // requires three arguments to be different from regular reducer and because of this https://github.com/mweststrate/immer#pitfalls (pitfall 3)
  // type checked to return void
  @Action(ActionCatPlay, ActionCatBeAwesome)
  wasteEnegry(state: DeepReadonly<IReducerCatState>, draft: IReducerCatState, action: ActionCatPlay | ActionCatBeAwesome) {
    draft.energy -= action.payload
  }
}

const reducer = ReducerCat.create()
```

**Comment by markerikson** [comment]
Thanks for the suggestion, but nope, not using classes for reducers.  Not idiomatic Redux usage.
