### ISSUE TITLE
Deleting deep state element fails

### ISSUE THREAD

**Issue by wvlia5** [reduxjs/redux-starter-kit#114]
I have 2 similar event handlers:

This one doesn't work:

```javascript
deleteBars(state,{barNames}){
    barNames.forEach(n=>{delete state.someProp.bars[n]})
}
```

But this one works:

```javascript
deleteFoos(state,{fooNames}){
    fooNames.forEach(n=>{delete state.foos[n]})
}
```
Both `state.foos` and `state.someProp.bars` are Objects

May it be that immer fails beyond certain depth level?

I have checked that in the non-working case, after the for loop `state` is an Object with prop `base` and `copy`. In `copy` the deleted items are effectively absent, but after the event is handled, the rest of my application still sees an unmodified state

**Comment by markerikson** [comment]
Huh, interesting.

Can you put together a CodeSandbox that reproduces the issue?

**Comment by wvlia5** [comment]
I will try to.
Correction to what I said before:

After the event is handled, modified state arrives correctly at the `render` function of my component, with the correct items absent. However, it renders as if _other_ items had been deleted.

Example:

initially we have:

`{a:{...}, b:{...}, c:{...}, d:{...}, e:{...}, f:{...}}`

if I delete b and c, the `render` function receives (or at least that is what console.log says):

`{a:{...}, d:{...}, e:{...}, f:{...}}`

but renders as if it had received

`{a:{...}, b:{...}, c:{...}, d:{...}}`

**Comment by wvlia5** [comment]
I think this has nothing to do with Redux, but rather with controlled/uncontrolled components

In the working case I am setting de value of an input, while in the non-working case I am setting the defaultValue of an input (that's what I need). So the previous defaultValue remains and is not reset with the new data. Arrgggghhh

Any tips on how to solve this, appreciated
