### ISSUE TITLE
How to create skeleton project?

### ISSUE THREAD

**Issue by scheung38** [reduxjs/redux-starter-kit#115]
npm install --save redux-starter-kit

and then next guide provides all the code, are we not missing user guide, how to create it from redux-starter-kit

as I am struggling to find the CLI command to create using it

**Comment by markerikson** [comment]
Redux Starter Kit doesn't have any CLI commands.  It's a library, with a set of functions you call from your own app.

We do need to add some kind of a tutorial page, but in general, see the [Usage Guide](https://redux-starter-kit.js.org/usage/usage-guide) for examples of how to use it.

**Comment by aikidoshi** [comment]
A complete working codepen or something that demonstrates all of the features and their correct usage would be fantastic. Please ...

**Comment by markerikson** [comment]
@aikidoshi : agreed, but unfortunately docs work for RSK is low on my own priority list atm.  Hopefully the [Usage Guide](https://redux-starter-kit.js.org/usage/usage-guide) at least helps some.

**Comment by aikidoshi** [comment]
Thanks Mark, the docs are great, thanks for taking the time to at least acknowledge my email.
Have a good Easter!
Steve Bond
________________________________

**Comment by andrey-prokhorov** [comment]
It is confusing that you mention `redux-starter-kit` works in the spirit of  `create-react-app` in your [quick start](https://redux-starter-kit.js.org/introduction/quick-start) page, but no skeleton project is generated.

**Comment by markerikson** [comment]
@andrey-prokhorov : `apollo-boost` doesn't generate projects either.  Both `apollo-boost` and RSK are just libraries you add to your project, just like React itself.  The comparison with CRA is about the "good defaults and batteries included out of the box" aspect, not saying that this is a CLI that creates a project.

**Comment by markerikson** [comment]
Resolved now that the tutorial pages are up in the docs: https://redux-starter-kit.js.org/tutorials/advanced-tutorial
