### ISSUE TITLE
UMD package does not work in browser environment

### ISSUE THREAD

**Issue by ukch** [reduxjs/redux-starter-kit#124]
Following the quickstart, I attempted to load the [UMD version](https://unpkg.com/redux-starter-kit/dist/redux-starter-kit.umd.js) via a `<script>` tag, but I received the error `process is not defined`. I did a bit more digging and can see calls to `require` in the script, which makes me think the compile process is not functioning correctly.

**Comment by ukch** [comment]
I have tested version 0.3.3 and it works as expected, so the issue must have been introduced in the 0.4.x series.

**Comment by markerikson** [comment]
Hmm.  Yeah, I added a dev/prod check to try to dynamically load the runtime error-checking middleware.

This would probably involve some fiddling with the Rollup build config.  In fact, we probably ought to have both a "dev" and a "prod" build, if we don't already.

I'm afraid I don't have time to look into this myself atm.  If you can give it a shot and file a PR, I'd really appreciate it.

**Comment by markerikson** [comment]
Looking at this a bit more, and specifically at https://unpkg.com/redux-starter-kit@0.5.0/dist/redux-starter-kit.umd.js :

yeah, we do reference `process` in there, and there's no prod/minified build.  We should update the build process to do both.

**Comment by markerikson** [comment]
I just published https://github.com/reduxjs/redux-starter-kit/releases/tag/v0.6.1 , which _should_ fix the issue.  

I'd appreciate it if you could try out both the dev and prod builds and confirm that they both work right.

**Comment by markerikson** [comment]
Closing as this should be fixed.  Let me know if there's any other problems!
