### ISSUE TITLE
Error in typescript with project references

### ISSUE THREAD

**Issue by B3zo0** [reduxjs/redux-starter-kit#125]
So I have a monorepo with multiple typescript libs. I wanted to try redux-starter-kit in one of my lib. But after adding that as a dependency I can not build without error because I see 
```
error TS6307: File '/mnt/c/dev/github/sensenet/sn-client/node_modules/redux-starter-kit/src/configurestore.ts' is not in project file list. Projects must list all files or use an 'include' pattern.
```
The redux-starter-kit works great in a repo where project references are not turned on. The source of the problem might be the index.d.ts file in the root of the project because it points to the files located in src.

**Comment by jamiewinder** [comment]
I've just discovered the same thing. I see you've added a pull request to fix this, but did you figure out a workaround at all?

**Comment by B3zo0** [comment]
@jamiewinder not found a workaround sadly
