### ISSUE TITLE
Unable to delete state property

### ISSUE THREAD

**Issue by akana** [reduxjs/redux-starter-kit#135]
Hi!! Given code the below
```javascript
{
  customer: {
    itemsById: {
      1: {
        id: 1,
        firstName: 'Burr',
        lastName: 'Heyward',
      },
      2: {
        id: 2,
        firstName: 'Devin',
        lastName: 'Basler',
      }
  }
}

const remove = ( state, action ) => {
  delete state.customer.itemsById["1"]
}

const customerPageSlice = createSlice( {
  slice: 'customer',
  initialState: initialState,
  reducers: {
    remove: remove,
  }
} )
```

After executing `store.dispatch({type : "customer/remove"})`, the state isn't changed. Do i make any mistake or is it a bug?

Any help would be appreciated!!!

**Comment by denisw** [comment]
Your `remove` reducer seems to assume that it receives the complete store state, and hence tries to access `state.customer.itemsById`. However, what it actually receives is just the `customer` slice of the state, so the correct path would be simply `state.itemsById`.

**Comment by akana** [comment]
```javascript
```

**Comment by akana** [comment]
sorry that i accidentally type Ctrl+Enter. So comment is submitted and closed. By the way, let me revise the code : 
```javascript
const initialState = {
  customer: {
    itemsById: {
      1: {
        id: 1,
        firstName: 'Burr',
        lastName: 'Heyward',
      },
      2: {
        id: 2,
        firstName: 'Devin',
        lastName: 'Basler',
      }
  }
}

const remove = ( state, action ) => {
  delete state.customer.itemsById["1"]
}

const customerPageSlice = createSlice( {
  slice: 'customer',
  initialState: initialState,
  reducers: {
    remove: remove,
  }
} )
```

version

- redux-starter-kit : 0.4.3
- immer : 2.1.5

**Comment by denisw** [comment]
What I meant is that you need to change:

```js
const remove = ( state, action ) => {
  delete state.customer.itemsById["1"]
}
```

to:

```js
const remove = ( state, action ) => {
  delete state.itemsById["1"]
}
```

because the `state` argument` is already the value of `<rootState>.customer`.
