### ISSUE TITLE
Has `createSelector` been removed in 0.5.0?

### ISSUE THREAD

**Issue by jrsinclair** [reduxjs/redux-starter-kit#137]
After upgrading from 0.4.3 to 0.5.0 I can no longer import `createSelector()` from `redux-starter-kit`. It doesn't appear to be exported anywhere in [index.ts](https://github.com/reduxjs/redux-starter-kit/blob/master/src/index.ts) either. Has  it been removed? Do I need to install selectorator as a separate dependency now?

**Comment by markerikson** [comment]
Whoops!  Looks like the export got accidentally removed in the process of converting the TS build process.

I'll see if I can re-add that tonight.

**Comment by jrsinclair** [comment]
FWIW, we are using the string selector feature. It wouldn't be the end of the world if we had to switch (I read what you're thinking in #82), but I do find it convenient.

**Comment by markerikson** [comment]
Yeah, that's what I was thinking of.  Thanks for the feedback!

**Comment by markerikson** [comment]
@jrsinclair : okay, just published 0.5.1, which I _think_ should fix the issue.  Can you try that and confirm?

For reference, this was caused by the changes in #128 .

**Comment by jrsinclair** [comment]
Worked like a charm. Thanks. Really appreciate the quick response.

**Comment by markerikson** [comment]
Sure, sorry about that!
