### ISSUE TITLE
UI performance slow when devtools are enabled

### ISSUE THREAD

**Issue by thomasjensen1194** [reduxjs/redux-starter-kit#147]
Hi. I'm running chrome with the redux-devtools and have them enabled as such:

```
export const store = configureStore({
  reducer: pReducer,
  middleware,
  devTools: true
});
```

Is it possible to add `maxAge `to the devTools? I think the log of the many actions is getting so big, that it's compromising the performance of the UI. Cheers.

**Comment by markerikson** [comment]
As of 0.5.0, you should be able to pass an options object as the `devTools` parameter, and that will be passed to the DevTools Extension setup:

https://redux-starter-kit.js.org/api/configurestore#devtools
