### ISSUE TITLE
Persisting with redux-persist

### ISSUE THREAD

**Issue by rodelrebucas** [reduxjs/redux-starter-kit#150]
I created the store using configureStore
I have an error when using redux-persist  tries to rehydrate my store.

Error:

> A non-serializable value was detected in an action, in the path: `%s`. Value: %o
> Take a look at the logic that dispatched this action:  %o.
> (See https://redux.js.org/faq/actions#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants), register, [Function register], Object {
>   "register": [Function register],
>   "rehydrate": [Function rehydrate],
>   "type": "persist/PERSIST",
> }

Is redux-persist even supported? I haven't seen any samples with redux persist integration.

**Comment by markerikson** [comment]
It seems like Redux-Persist tries to put a function into the action.  That works, it's just not the ideal approach, so `configureStore()` will warn you about that by default.

You can always override the `middleware` option to `configureStore()` to leave out the serialization middleware.
