### ISSUE TITLE
How do I set initial value of a reducer to [] with createReducer in typescript?

### ISSUE THREAD

**Issue by ZYinMD** [reduxjs/redux-starter-kit#151]
We know that in typescript, you can't do 
```ts
let foo = [];
foo.push('bar');
```
because foo is set to `never[]` by default.

Now in my code:
```js
const myReducer= createReducer([], {
  'FOO': (state, { bar }) => {
    state.push(bar)
  },
});
```

It doesn't compile, because I can't push into state. What's the recommended work-around? Thanks!

**Comment by markerikson** [comment]
My guess is that you need to do something like `createReducer([] as SomeType[], reducers)`.

**Comment by ZYinMD** [comment]
Oops, sorry I thought I tried that and it didn't work. But now it's working, I must have had some other syntax error when I tried. Sorry my bad. Closing.
