### ISSUE TITLE
Object.keys: argument is not an Object in redux-starter-kit.esm.js

### ISSUE THREAD

**Issue by paul-mcgrath** [reduxjs/redux-starter-kit#152]
Hi there,

I'm having an issue using this project with IE11, specifically with this error message in the redux-starter-kit.esm.js file:
> Object.keys: argument is not an Object

The issue occurs in the following method on the third line :
```function _objectSpread(target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i] != null ? arguments[i] : {};
    var ownKeys = Object.keys(source);  // <-- error occurs here

    if (typeof Object.getOwnPropertySymbols === 'function') {
      ownKeys = ownKeys.concat(Object.getOwnPropertySymbols(source).filter(function (sym) {
        return Object.getOwnPropertyDescriptor(source, sym).enumerable;
      }));
    }

    ownKeys.forEach(function (key) {
      _defineProperty(target, key, source[key]);
    });
  }

  return target;
}
```

From digging a bit deeper, it seems to try and call `Object.keys` on a value of **false**, which then fails in IE11.

The current behaviour in Chrome is to return an empty array when calling `Object.keys()` on a non-object, but polyfilling IE11's `Object.keys()` method has so far been unsuccessful.

Should this starter kit work with IE11 out of the box, or is there some guidance on compatibility?

**Comment by markerikson** [comment]
Hmm.  I'll be honest and say I've put zero thought into browser compat issues so far.

That particular chunk of code appears to be a Babel polyfill for the object spread operator.

What input and stack trace is leading to that particular edge case getting hit?

**Comment by markerikson** [comment]
Closing due to lack of actionable feedback.

**Comment by realignedTech** [comment]
In case anyone comes here via google and is looking for a fix, including the [es6-shim](https://github.com/paulmillr/es6-shim) resolves the issue.

**Comment by felixpaq** [comment]
Even simpler fix, just set the devTools option to an empty object in the configureStore
```javascript
export default configureStore({
  reducer: rootReducer,
  devTools: {}
});
```
