### ISSUE TITLE
ReferenceError: Cannot access 'store' before initialization in redux

### ISSUE THREAD

**Issue by marcosroot** [reduxjs/redux-starter-kit#167]
Here is something very funny, I create the store in a separate file, and can get its properties (dispatch, getState etc), confirm this with a console.log:

```   
    const store = getStore();
    console.log(store)
```

But when I try to use this same constant in another file, it returns me undefined and I get this error described in the title of the question:

```
    import store from "store";
    console.log("STORE: ", store); // undefined
```

What's the point? And how can I get access to this? I tested trying to gain access to the store through a file where I create an axios instance.

The complete code of the store:

```
    // app/store/index.js
    const history = createBrowserHistory();
    const sagaMiddleware = createSagaMiddleware();
    const middleware = [
    	...getDefaultMiddleware(),
    	routerMiddleware(history),
    	sagaMiddleware,
    ];
    const reducer = createReducer(history);
    
    
    // store
    const getStore = () => {
    	const store = configureStore({
    		reducer,
    		middleware,
    		devTools: process.env.NODE_ENV !== "production",
    	});
    
    	store.subscribe(() => {
    		saveState(toLocalStorage(store.getState()));
    	});
    
    	return store
    }
    
    const store = getStore();
    sagaMiddleware.run(saga);
    
    export default store;
    export { history };
```

The file that i get the store:

```
    // app/api/private/index.js
    import store from "app/store";
    
    // ...
    // this raise the error
    const { access, refresh } = store.getState().auth.token;
    // ...
```

**Comment by markerikson** [comment]
Answered this on Reddit, but pasting here too:

You have a circular dependency issue:

- [`http/private`](https://gitlab.com/marcosroot/webstation.dev-client/blob/0546f746eab2229484e3388269ef8645477a32fd/src/http/private.js) : `import store from "app"`
- [`components/headerNav`](https://gitlab.com/marcosroot/webstation.dev-client/blob/0546f746eab2229484e3388269ef8645477a32fd/src/components/headerNav/index.jsx): `import apiPrivate from "http/private";`
- and then `app` imports your component tree

So, because of that, `http/private` is going to get loaded first and try to grab the store from `app`, except `app` hasn't actually been loaded yet because it's waiting on the component tree to be imported.

Don't do that :)

I'd suggest moving the `configureStore()` call into a separate `store.js` file instead, to break the dependency issue.

**Comment by gjthompson1** [comment]
I was doing a refactor and got this error. For me the issue was order of imports.

**Comment by msutkowski** [comment]
> I was doing a refactor and got this error. For me the issue was **order of imports**. (which caused the circular dependency issue).

Yup, without seeing your code that you refactored, the order of imports will still be flaky. You most likely need to call your intereceptors like:

```
// interceptors.js
export default {
  setup: store => {
    axios.interceptors.response.use(
      response => response,
      error => {
       // whatever you do
      }
    );
  },
};
```
```
// index.js
// other imports
// import * as AxiosInterceptors from './interceptors';

AxiosInterceptors.setup(store);

doYouRenderThing();
```

**Comment by ThukuWakogi** [comment]
Many of the solutions proposed across the internet didn't work for me as I had to make lots of changes in my project. This solution has worked for me.

Require the store and export the state
```ts
// src/redux/utils.ts

import { RootState } from './store';

export const getReduxState: () => RootState = () => require('./store').default.getState();
```

Then use it in any part of the app
```ts
// src/services/api/todo

export const addTodo = body =>
  axios.post(
    '/todo/',
    body,
    { headers: { Authorization: `Bearer ${getReduxState().authentication.token?.access}` } },
  );
```

**Comment by markerikson** [comment]
Hmm. I really can't recommend that approach, unfortunately :(

Our normal answer is "try to avoid accessing the store directly in the first place" :)

But if you _must_ do it, our fallback answer is to inject the store into files that need it, via a setter:

https://redux.js.org/faq/code-structure#how-can-i-use-the-redux-store-in-non-component-files

**Comment by markerikson** [comment]
@coderSamrat per the discussion, _don't_ import the store directly. See:

- https://redux.js.org/faq/code-structure#how-can-i-use-the-redux-store-in-non-component-files
