### ISSUE TITLE
calling a reducer generated by "createReducer" without parameters give error

### ISSUE THREAD

**Issue by yairEO** [reduxjs/redux-starter-kit#171]
In my Jest test, this results in an error:

> returns initial state by default when no state & no matching reduce key found
> TypeError: Cannot read property 'type' of undefined

    const result = reducer();
    expect(result).toEqual(initialState);

But this works:

    const result = reducer(initialState, {type:""});
    expect(result).toEqual(initialState);

## My reducer is quite simple:

```javascript
import { createReducer } from 'redux-starter-kit';
import { SIDEMENU_COLLAPSE_TOGGLE } from './actions';

const initialState = {
  isCollapsed: false
};

const handlers = {
  [SIDEMENU_COLLAPSE_TOGGLE]: (state, { toggleState }) => {({
    ...state,
    isCollapsed:
      typeof toggleState === 'undefined' ? !state.isCollapsed : toggleState
  })}
}

const reducer = createReducer(initialState, handlers)

export { initialState };

export default reducer;
```

I expect the reducer to already have the *initialState* when it was initialized from the `createReducer` method and also to have a default return (the state) when no *action type* parameter is passed

**Comment by markerikson** [comment]
That is incorrect.  A Redux reducer function _always_ expects an actual action object to be passed as the second parameter, by definition:

https://redux.js.org/basics/reducers

There's no such thing as a "default action".
