### ISSUE TITLE
Redux-immutable-state-invariant is throwing errors when I use createSlice

### ISSUE THREAD

**Issue by derindutz** [reduxjs/redux-starter-kit#181]
Hey Mark! I've been trying to incorporate RSK's suggestions into our production codebase since we talked at RR :) Redux-immutable-state-invariant is throwing errors whenever my slice reducers get called. My understanding was immer would prevent these errors. Any thoughts on why errors are getting thrown?

In case it helps, I've attached relevant files below. The most important one is my slice file (activitesSlice.ts). I've also included store.ts, combine-slice-reducers-with-global-state-reducer.ts, and a custom configure-store.ts which allows for the combination of slice reducers and the single reducer. We're going to slowly convert everything to slice reducers but need to support the single reducer while we migrate things over.

[redux-immutable-state-invariant-error-relevant-code.zip](https://github.com/reduxjs/redux-starter-kit/files/3553170/redux-immutable-state-invariant-error-relevant-code.zip)

**Comment by derindutz** [comment]
And here's the stack trace in case it's helpful (I blurred out the parts that probably aren't helpful):
![error](https://user-images.githubusercontent.com/5715140/63898272-217ee400-c9ad-11e9-8008-4807f43acd64.png)

**Comment by derindutz** [comment]
I'm also seeing discrepancies in the redux devtools. I'm not seeing state diffs associated with createSlice reducers and they're showing up as associated with other actions:

For example, here is my non-createSlice SET_DEVICE_INFORMATION action:
<img width="1196" alt="Screen Shot 2019-08-28 at 4 04 58 PM" src="https://user-images.githubusercontent.com/5715140/63898476-01035980-c9ae-11e9-8aaa-c8875212973b.png">

Weirdly, it's showing an isLoadingById diff:
<img width="1194" alt="Screen Shot 2019-08-28 at 4 04 53 PM" src="https://user-images.githubusercontent.com/5715140/63898514-242e0900-c9ae-11e9-82b3-bb113da87e8b.png">

And then here's the activity/activityFetchRequest action (created with createSlice):
<img width="1196" alt="Screen Shot 2019-08-28 at 4 05 04 PM" src="https://user-images.githubusercontent.com/5715140/63898535-3b6cf680-c9ae-11e9-9a5d-694cb182ef18.png">

And the diff is empty (it should have the isLoadingById diff from above):
<img width="1196" alt="Screen Shot 2019-08-28 at 4 05 10 PM" src="https://user-images.githubusercontent.com/5715140/63898548-4cb60300-c9ae-11e9-9741-cbdac2937635.png">

I've read through all the docs multiple times and can't see what could be causing this. Any help would be much appreciated!

**Comment by markerikson** [comment]
Huh.  That _is_ extremely weird.

Glancing at the activities slice, I don't immediately see any issues.  

I unfortunately don't have time to dig into this right at the moment.  I may have a bit of time over the weekend.  Please let me know if you figure anything out.

**Comment by ramyareye** [comment]
for me works with 
`yield put({payload: {id}, type: activityFetchRequest.type});`
instead of 
`yield put(activityFetchRequest({ id }));`

**Comment by derindutz** [comment]
@markerikson Yeah! Thank you for glancing over the activities slice file! I'm very confused too. I'll definitely let you know if I figure anything out.

@ramyareye I don't think that'll make a difference. activityFetchRequest({ id }) generates that exact same object you suggest using
![image](https://user-images.githubusercontent.com/5715140/63962272-648d9580-ca47-11e9-91c5-f940be05d096.png)

**Comment by derindutz** [comment]
I've been trying multiple different things but to no avail :( 

For example, I tried to return a new state object instead of modifying the immer draft am still getting the same issue: 
```
return {
  ...state,
  isLoadingById: {
    ...state.isLoadingById,
    [id]: true,
  },
};
```

I also tried calling it from outside redux saga but the state mutation error persisted there too.

Any help would be much appreciated!

**Comment by derindutz** [comment]
I've been trying multiple different things:

I tried to return a new state object instead of modifying the immer draft am still getting the same issue: 
```
return {
  ...state,
  isLoadingById: {
    ...state.isLoadingById,
    [id]: true,
  },
};
```

I also tried calling it from outside redux saga but the state mutation error persisted there too.

I then changed the source for createReducer.ts to remove immer:
```
export function createReducer<S, CR extends CaseReducers<S, any> = CaseReducers<S, any>>(
  initialState: S,
  actionsMap: CR
): Reducer<S> {
  return function(state = initialState, action): S {
    // @ts-ignore createNextState() produces an Immutable<Draft<S>> rather
    // than an Immutable<S>, and TypeScript cannot find out how to reconcile
    // these two types.
    const caseReducer = actionsMap[action.type];
    return caseReducer ? caseReducer(state, action) : state;
    // return createNextState(state, (draft: Draft<S>) => {
    //   const caseReducer = actionsMap[action.type];
    //   return caseReducer ? caseReducer(draft, action) : undefined;
    // });
  };
}
```
The errors still didn't go away! 🤯

So now it doesn't seem like it's immer. Any thoughts on what else it could be? Any help would be much appreciated!

**Comment by markerikson** [comment]
I'm pretty stumped at this point, tbh.  

What happens if you use a vanilla JS reducer here instead of RSK?

Is there any other part of the codebase that might somehow be interacting with this particular dispatch?  A middleware, maybe?

**Comment by derindutz** [comment]
I figured it out!! The problem was with my re-implementation of combineSliceReducers to include a global state reducer (in combine-slice-reducers-with-global-state-reducer.ts). I was first calling the global state reducer on the state and then calling each of the slice reducers in turn and using what was returned by the global state reducer as a parameter. Redux-immutable-state-invariant caught this (correctly!) as a mutation of the state.

Here's my correction: https://gist.github.com/derindutz/b90adc31e00bc2ada2c7f878990e0892. 

I'd prefer to use something supported by the community and well-tested. Are you aware of any redux-supported implementations of combineReducers that allow for a global state reducer? If not, could you take a look at my gist and see if it looks good? If so and if you think it'd be helpful to other people (who like me may be slowly migrating from a global reducer to slice reducers and want to support both), I can submit it as a PR to redux.

**Comment by markerikson** [comment]
Have you considered using `combineReducers` as normal, and then running a second reducer in sequence after that?

I talked about that approach in these articles:

https://redux.js.org/recipes/structuring-reducers/beyond-combinereducers

https://blog.isquaredsoftware.com/2017/01/practical-redux-part-7-forms-editing-reducers/

**Comment by derindutz** [comment]
By "global state reducer" I mean a reducer that operates on the entire state. Imagine you started from scratch with no slice reducers and then let it get really big. That's my global state reducer. 

A lot of my code assumes that it's operating on the entire state. For example, I have `state.usersById` and a bunch of selectors that assume `usersById` will be on state. Moving all of these keys to a slice reducer would be too big of a project to take on right now, so I want to slowly incorporate slice reducers.

The issue with using `combineReducers` in my reducer chain and passing the return value of `combineReducers` to my global state reducer is that combineReducers only returns a state object that has the keys that are passed to combineReducers as slice names. I can't do this since I'll lose all the keys such as `usersById` that are in the global state. Further, `combineReducers` checks if the number of keys in the state is equal to the number of slice names passed in which will never be the case for me.

So it seems to me like I need to write a custom version of `combineReducers` but I'd love to be corrected if I'm wrong!

**Comment by markerikson** [comment]
Right, that's what I talk about handling in those two posts I linked - use `reduceReducers()` to run multiple reducers in sequence, vs `combineReducers` "in parallel" behavior.  

I was more asking about what the logic in your "global" reducer is actually doing.  Are you saying there's a mismatch between the output of `combineReducers` and what the entire state tree looks like?

**Comment by derindutz** [comment]
Yep there's an output mismatch. So I don't think running the reducers in sequence would work.

For example, let's say the state starts out as:
```
{
    usersById: {
        id1: {
            name: "Mark"
        }
    },
    isUserLoadingById: {
        id1: false
    },
    activities: {
        byId: {
            id2: {
               name: "Running"
            }
        }
    }
}
```

And this is how we've configured our store:
```
const store = configureStore({
  globalStateReducer: reducer,
  sliceReducers: {
    [activitiesSliceName]: activitiesReducer,
  },
  middleware,
  devTools: process.env.NODE_ENV !== 'production',
  preloadedState: initialState,
});
```

Now if we run `combineReducers` and pass in `sliceReducers` above, `combineReducers` will output:
```
{
    activities: {
        byId: {
            id2: {
               name: "Running"
            }
        }
    }
}
```
As you can see, all the non-slice-reducer stuff in the state is dropped.

**Comment by markerikson** [comment]
Yeah, our own `combineReducers` is opinionated in that it expects every key to be backed by a slice reducer, and I think it drops values that aren't.

Using your own `combineReducers` reducer function is going to be the right approach here.

**Comment by derindutz** [comment]
Awesome! Well thank you very much for everything!! I really appreciate your help and advice and all the work you're doing to improve the developer landscape :)
