### ISSUE TITLE
Investigate switching or updating build tooling

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-starter-kit#188]
We currently have a build setup that started off as a clone of Redux's setup, and then was modified when we did the conversion to TS.

Redux itself is currently being rewritten in TS, so there's updates to its build tooling going on atm.  Meanwhile, tools like https://github.com/palmerhq/tsdx and https://github.com/developit/microbundle are supposed to make it easier to build and publish packages that have good output.

I'm open to updates to our build setup, and would appreciate it if someone could take the time to evaluate what we currently have for RSK compared to the other options.

I did briefly play with TSDX, and remember running into some pain points with how it could be configured.  I don't remember specifics, although I think part of it may have been how it tried to name output files (especially UMD builds).

Related issues: #78 (can't tree shake properly due to dependencies)

**Comment by RichiCoder1** [comment]
I've recently moved one or two libraries over to TSDX with a generally good experience. I could likely help with this, though I'm curious what issues you had? As well as what targets you're still chiefly aiming to support and any quirks you're aware of with the current build/test setup?

**Comment by markerikson** [comment]
Off the top of my head:

- It changed the name of all the output files ( `redux-starter-kit.[type].js` -> `reduxStarterKit.[type].js`)
- Don't think it let me do both a minified and production UMD build
- For RSK, I'm pretty sure I want an actual bundled UMD build that includes Redux, Reselect, Immer, etc, all in one bundle.  TSDX extracted those as external global dependencies.

So, largely UMD-related, I think.

**Comment by RichiCoder1** [comment]
Cool beans! (1) and (3) are just rollup defaults I believe, so should just be tweaking some knobs. 

For 
> Don't think it let me do both a minified and production UMD build

I'm not sure I follow? Did you mean a dev and prod build?

**Comment by markerikson** [comment]
Heh, yeah, wrong phrasing :)

**Comment by RichiCoder1** [comment]
That doesn't sound insurmountable. I'll give it a go hopefully this week or weekend!

**Comment by markerikson** [comment]
Great, thanks!

**Comment by RichiCoder1** [comment]
@markerikson I'm finally getting around to it, and looking into it I'm not sure that'd you'd actually gain much moving to TSDX/Microbundle. If only just cuz it looks like you've already good a pretty optimized rollup and lint going. It would slim down you scripts a little and get you more of a "standard" build setup, but that's up to you. If you're still game I can knock this out :)

**Comment by markerikson** [comment]
I'd at least be curious to see how it would compare, yeah.

Also, if you're looking into this, any chance you could also glance at #55 and #78 , and figure out if there's some way to improve our tree shaking ability?  If not, no worries, just thought I'd check.

**Comment by RichiCoder1** [comment]
I'll getcha a PR for comparisons then!

No expert on tree shaking, but I'll take a look! Been trying to do those sort of optimizations for our work packages

**Comment by markerikson** [comment]
Resolved via #212 .
