### ISSUE TITLE
isActionType Type guard

### ISSUE THREAD

**Issue by jamiewinder** [reduxjs/redux-starter-kit#194]
An `isActionType` type guard would be handy. Implementation-wise, it'd just be a case of:

```typescript
export function isActionType(action, creator) {
    return action.type === creator.type;
}
```
But with the correct TypeScript typings, this would be quite powerful. I've tried adding this myself, but I appear to have an issue with slice actions as the following implementation only appears to work for actions created with `createAction`:
```typescript
export function isActionType<TPayload, TType extends string>(
    action: PayloadAction,
    creator: PayloadActionCreator<TPayload, TType>
): action is PayloadAction<TPayload, TType> {
    return action.type === creator.type;
}
```

**Comment by jamiewinder** [comment]
I eventually stumbled onto the reason why my `isActionType` doesn't work with `createSlice` actions; the 'type' property is typed as 'string' rather than a constant.

**Comment by markerikson** [comment]
I know someone mentioned something about the way we concatenate the slice name and the reducer name resulting in a `string` instead of the specific constants as a literal.  Not sure there's anything we can do about that atm.

**Comment by markerikson** [comment]
I don't see a specific need to include this in RSK itself atm, so closing.

**Comment by challet** [comment]
> I don't see a specific need to include this in RSK itself atm, so closing.

I'm using it for redux-saga [take effect](https://redux-saga.js.org/docs/api/#takepattern) as a function predicate

**Comment by EskiMojo14** [comment]
this issue is over 5 years old 😅 

for reference, we now have `.match` type guards attached to each RTK action creator, and Redux Saga specifically supports passing the action creator itself as well.

**Comment by challet** [comment]
I know it is old :) Thank you for the hint !
