### ISSUE TITLE
Outdated selectorator references

### ISSUE THREAD

**Issue by darekkay** [reduxjs/redux-starter-kit#196]
In #191, the selectorator library was removed. However, the [README](https://github.com/reduxjs/redux-starter-kit/blame/master/README.md#L35) and the [quickstart](https://github.com/reduxjs/redux-starter-kit/blame/04cdb02a20c227f76dece62f2785bdac47bc6768/docs/introduction/quick-start.md#L34) still mention this library.

**Comment by markerikson** [comment]
Yep, forgot to update those when I yanked the lib out.  Would you like to file a PR to remove those mentions?

**Comment by markerikson** [comment]
Resolved by #199 .
