### ISSUE TITLE
Definition for rule '@typescript-eslint/consistent-type-assertions' was not found

### ISSUE THREAD

**Issue by nidble** [reduxjs/redux-starter-kit#198]
Hi all,

As usual, I cloned the main repo and executed `npm install`/`npm start`. But unfortunately app crashed very soon reporting the error in the subject.

From this thread https://github.com/typescript-eslint/typescript-eslint/issues/863 I fixed my local setup replacing into package.json react scripts lib: `"react-scripts": "^3.1.2",`.

I hope it helps. Thanks for your work.

**Comment by markerikson** [comment]
Ah... _what_ repo did you clone, and for what purpose?

This is a library, not an app.  

I'm kind of confused, and this doesn't seem like an actual issue with this library.

**Comment by nidble** [comment]
Whops! I'm sorry @markerikson. 

My fault, the correct repo is https://github.com/markerikson/rsk-github-issues-example. What do you prefer? I can repost this issue on the correct repo, or considering the owner :), do I leave its to you?

**Comment by markerikson** [comment]
Hmm.  I would be very surprised if there was a real problem with that repo - it's just a standard CRA project.  

If you can consistently reproduce the problem, then maybe file an issue there, but I'm not sure there's really anything I can do about it.  Also, I suggest trying `yarn` instead of `npm`.

**Comment by nidble** [comment]
Hi Mark, I tried with `yarn` and everythings works fine. Currently the "issue" is only with npm (6.9.0). The steps to get involved are quite simple: `npm install && npm run start`.

**Comment by markerikson** [comment]
Yeah, I really don't see anything actionable to do here.  It's a plain standard CRA app, and installing the packages works with Yarn.  If NPM is having problems, that's outside the scope, and I can't think of anything I could change to affect that.

**Comment by nidble** [comment]
Yes, sure. My comment was only to give you an insight about. And a reference to other people that meeting this issue. Thanks.

**Comment by markerikson** [comment]
Yep, appreciate the heads-up!

**Comment by markerikson** [comment]
So, this is bizarre.  I just started seeing this myself, in both my local repo and in CI.
