### ISSUE TITLE
Typing of store.dispatch when used to dispatch a thunk

### ISSUE THREAD

**Issue by ZYinMD** [reduxjs/redux-starter-kit#203]
If I do something like this (simplified):
```js
import store from '../../store';

const myThunk = () => dispatch => {
  dispatch({ type: 'HELLO_WORLD' });
}

// @ts-ignore
store.dispatch(myThunk());
```

It does work as I intended. However, if I remove the `// @ts-ignore`, Typescript will complain that "you must dispatch an action", and won't compile.

To explain why I do this, `myThunk` is sometimes dispatched by a react component, and some other times dispatched by a utility function which doesn't have a proper `dispatch` in scope, so I use `store.dispatch` directly.

**Comment by markerikson** [comment]
Try declaring the type of `myThunk` and its return value, per the Advanced Tutorial:

https://redux-starter-kit.js.org/tutorials/advanced-tutorial
