### ISSUE TITLE
Update Travis to test against multiple versions of TypeScript

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-starter-kit#216]
References: 

- https://github.com/reduxjs/redux-starter-kit/issues/82#issuecomment-542334266

> Could we please have the build & tests run for multiple TS versions? Something like the last 4 or 5 minor releases should catch quite a few bugs.

- #214
- #212

/cc @phryneas

**Comment by nickmccurdy** [comment]
What would you like to do with the default TypeScript version for development? It's currently 3.4.3, which is two minor releases and six months old. I think we should update it to the latest and test older releases like 3.4.x in CI.

**Comment by phryneas** [comment]
I'd build for distribution with 3.6, but also build with the others, just as a test.
