### ISSUE TITLE
Action is no longer re-exported from redux

### ISSUE THREAD

**Issue by mykter** [reduxjs/redux-starter-kit#221]
The advanced tutorial shows importing `Action` from rsk. This used to be possible, but it was removed in 0.9.0 - if this was intentional then the tutorial should be updated to import it from redux instead of rsk.

**Comment by markerikson** [comment]
Aaaand that looks like a bug.  Thanks!

**Comment by markerikson** [comment]
Published 0.9.1, which should fix this.  Thanks for the heads-up!  Let me know if you find any further issues.
