### ISSUE TITLE
Basic example demo at bottom of page does not work

### ISSUE THREAD

**Issue by alvincrespo** [reduxjs/redux-starter-kit#230]
If you visit the example at the bottom of the page for Basic Example, you'll see that the app does not run because "name" is not defined on slice created.

**Comment by alvincrespo** [comment]
I fixed it up with this codesandbox: https://codesandbox.io/s/counter-vanilla-createslice-redux-starter-kit-kd2z3

Unsure how to submit the patch to th original after forking (not sure that's a feature yet).

**Comment by markerikson** [comment]
Yep, I still need to go through and update all the tutorial repos and sandboxes to match the changes in 0.8.

**Comment by alvincrespo** [comment]
Any way I can help?

**Comment by markerikson** [comment]
Just updated this sandbox, and it should be working correctly now.
