### ISSUE TITLE
Typescript error in redux-starter-kit version 1.0.0

### ISSUE THREAD

**Issue by thomasjensen1194** [reduxjs/redux-starter-kit#232]
The following was working prior to updating to 1.0.0.

There is a possible type error in the createAction function. When supplying a payload, createAction throws a typescript error. The error is that the payload is not assignable to undefined or void.

Code:
> const LIKE = createAction('LIKE');
> dispatch(LIKE({ userId, commentId }));

Error:
> No overload matches this call.
  Overload 1 of 2, '(payload?: undefined): WithPayload<undefined, Action<"LIKE">>', gave the following error.
    Argument of type '{ userId: number; commentId: number; }' is not assignable to parameter of type 'undefined'.
  Overload 2 of 2, '(payload?: void): WithPayload<void, Action<"LIKE">>', gave the following error.
    Argument of type '{ userId: number; commentId: number; }' is not assignable to parameter of type 'void'.ts(2769)

The above works if typing the "like" variable to any as so (thereby passing the typescript check):
> const LIKE: any = createAction('LIKE');

**Comment by markerikson** [comment]
That looks like the type change for `createAction` that was introduced in v0.8.0:

https://github.com/reduxjs/redux-starter-kit/releases/tag/v0.8.0

We now effectively require that you specify the actual type of the payload explicitly, like `const LIKE = createAction<{userId: number, commentId: number}>("LIKE")`.

I'll go ahead and close this.  If there's something beyond that that's still a problem, please let us know.

**Comment by thomasjensen1194** [comment]
I see. I actually really like that. Thank you for your answer.
