### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by nickmccurdy** [reduxjs/redux-starter-kit#24]
1. Visit https://travis-ci.org/markerikson/redux-starter-kit
2. Enable repository
3. Revert 464aca1125f7ebf7d8711f6fe71af0134cc62811

**Comment by timdorr** [comment]
I turned it on: https://travis-ci.org/reduxjs/redux-starter-kit/builds/474472512

**Comment by timdorr** [comment]
OK, it works. I'll rebadge the readme.
