### ISSUE TITLE
Enhancers are added after middleware

### ISSUE THREAD

**Issue by KaRkY** [reduxjs/redux-starter-kit#39]
Hello,

Could the order of enhancers be switched? Now they are added after the middleware and that is why no middleware can see actions that are generated by enhancers.

Combination of redux-first-router and redux-saga is an example of this.

**Comment by markerikson** [comment]
Out of curiosity, what other enhancers do you have that are generating actions?

**Comment by markerikson** [comment]
Hmm.  Okay, so yeah, looking at the `redux-first-router` docs, they really do want their enhancer to be in front of the middleware.

My first instinct is that the point of `redux-starter-kit` is to be reasonably opinionated, and the point of `configureStore()` is to keep the end user from having to fiddle around with the store setup process.  In almost every Redux app I've seen, `applyMiddleware` comes first.  I'd say that if you need to care about the order of enhancers that way, you're probably better off writing the store setup logic by hand.

**Comment by KaRkY** [comment]
This is the only one for me it is not a problem to write few lines of code that never change. I just wanted to point that out for consideration.

**Comment by icopp** [comment]
My company's also using `redux-first-router`, so we're not able to use `configureStore` because of that.

Do any other projects break if enhancers come first?

**Comment by denisw** [comment]
If we wanted to support this, here is an idea: 

Export a special `configureMiddleware` value from `redux-starter-kit` (e.g., a symbol). If `configureMiddleware` is found in the `enhancers` array, apply middleware at that point; otherwise, apply middleware first.

```js
import { configureStore, configureMiddleware } from 'redux-starter-kit'

configureStore({
  reducer,
  // enhancer comes after middleware, as before
  store: [enhancer]
})

configureStore({
  reducer,
  // middleware comes after enhancer
  store: [enhancer, configureMiddleware]
})

configureStore({
  reducer,
  // middleware comes after enhancer1, before enhancer2
  store: [enhancer1, configureMiddleware, enhancer2]
})
```

**Comment by primozs** [comment]
Just a thought. This looks worse then original config.

**Comment by markerikson** [comment]
@primozs : if you want to configure the store "normally", there's nothing stopping you from using `createStore()` yourself directly.  That's kind of the point.  This is meant for the 80% use case

**Comment by primozs** [comment]
@markerikson I got confused when I saw only some parts of redux re exported. 
Cheers

**Comment by stvmachine** [comment]
The same problem happens with the enhancer of the `redux-offline`. Thumbs up for something like this!.

https://github.com/reduxjs/redux-starter-kit/issues/184

**Comment by markerikson** [comment]
I'm not particularly sold on the "magic `applyMiddleware` symbol" API design idea.  Does anyone have any other alternatives?

**Comment by markerikson** [comment]
Hmm.  We currently have https://redux-starter-kit.js.org/api/getDefaultMiddleware .  Maybe we need a `getDefaultEnhancers()` function too?

**Comment by phryneas** [comment]
What about accepting a callback as `enhancers`?

```typescript
function configureStore({
    // A single reducer function that will be used as the root reducer,
    // or an object of slice reducers that will be passed to combineReducers()
    reducer: Object<string, ReducerFunction> | ReducerFunction,
    // An array of Redux middlewares.  If not supplied, uses getDefaultMiddleware()
    middleware?: MiddlewareFunction[],
    // Enable support for the Redux DevTools Extension. Defaults to true.
    devTools?: boolean | EnhancerOptions,
    // Same as current createStore.
    preloadedState?: State,
    // An optional array of Redux store enhancers
    enhancers?: ReduxStoreEnhancer[] | (defaultEnhancer: ReduxStoreEnhancer) => ReduxStoreEnhancer[],
})
```

**Comment by markerikson** [comment]
Mmm... not sure I like the callback idea either.  I'm definitely leaning towards `getDefaultEnhancers()` at this point.

**Comment by phryneas** [comment]
But wouldn't the `getDefaultEnhancers()` result contain the `middlewareEnhancer` and thus not be available without knowing of the middlewares?

So you'd have to pass in the middlewares and end up with something like this:

```
const middlewares = [ ..., getDefaultMiddlewares(), ... ];
const store = configureStore({
  middlewares,
  enhancers: [ ..., getDefaultEnhancers(middlewares), ... ]
})
```

Having to pass in the middlewares at two different places might make for an a bit unwieldy API.

**Comment by markerikson** [comment]
Hmm. Excellent point.

Okay, I see what you're getting at with the callback thing.  In that case, would it make sense to do that for _both_ middleware and enhancers, and drop `getDefaultMiddleware` ?

**Comment by phryneas** [comment]
Either that, or enable both the current behaviour and the callback option. 

That might have not been clear from my initial post:
My initial idea was to allow either passing in an array (which would put the enhancers at behind the middleware, so the current behaviour) or optionally passing the callback for more control.

Similarly, `middlewares` could either receive an array (which would replace all middlewares, but be used with a - potentially deprecated - getDefaultMiddleware call) or passed a callback function.

**Comment by markerikson** [comment]
Resolved this by adding the callback idea for `enhancers` suggested by @phryneas .

**Comment by cmelion** [comment]
Are there any working examples using `redux-first-router` with `redux-toolkit` and Typescript published?
