### ISSUE TITLE
allow configuration of devtools via `configureStore`

### ISSUE THREAD

**Issue by wldcordeiro** [reduxjs/redux-starter-kit#40]
There's only really one config value I care about and configure in my store for the devtools and that's the `name` but to support that and others, could the [`devtools`](https://github.com/reduxjs/redux-starter-kit#configurestore) option accept a boolean or a config object?

I'm opening an issue and not a PR because I'd like to see if the boolean or object is a decent solution or if another would be preferred. I can PR this though. 😄

**Comment by markerikson** [comment]
I don't want to add _too_ much configuration, because part of the point of this package is to be opinionated, but that might be doable.  Toss up a PR and we'll see how it looks.
