### ISSUE TITLE
Unable to access previous or initial state

### ISSUE THREAD

**Issue by simonsmith** [reduxjs/redux-starter-kit#47]
How can I access the actual state, and not the Immer draft object? An example is when I want to use the initial state values for something in my reducer or when I'd like to compare against values in the current state before performing an update

```js
  NOTIFICATIONS_FULFILLED: (state, action) => {
    // state is the draft object from Immer
    // but I want to access the values set on my actual state
  },
```

Currently if I do `state.someProp` as you would in a normal reducer it just logs an empty Proxy

**Comment by markerikson** [comment]
Hmm.  At the start of the function, the draft object should represent the latest state, so you should be able to just use that as a starting point for any comparisons.

I guess I'm not really seeing what the issue is here.  Can you give a specific example, preferably with a CodeSandbox repro, of something you want to do that isn't working correctly?

**Comment by simonsmith** [comment]
Sure,

```js
import { createReducer } from "redux-starter-kit";
export const initialState = {
  result: []
};

const Notifications = createReducer(initialState, {
  TEST(state, action) {
    console.log(state.result);
  }
});

Notifications(undefined, { type: "TEST" });
```

In the above example I'd expect the log to be `[]` but it is instead a Proxy object. I'm presuming this is because the `draft` object is passed as the 'state' and the actual state object is inaccessible. So I can write to the state, but I cannot read from it. Or have I misunderstood?

A use case for this might be wanting to compare a value on the existing state object before deciding what to update on the draft

Link - https://codesandbox.io/s/2v017oozy0 (needs browser console)

**Comment by markerikson** [comment]
Immer is using a Proxy to wrap the state object, but as far as I know it should still let you access the underlying state as normal.

If I do `console.log(state.result.length)` in that sandbox, I see it print 3, as expected.

**Comment by simonsmith** [comment]
Ah, okay. I think that even though I'm not seeing `[]` I can still access things like `.map()` and `.length`. 

Thanks for your time!
