### ISSUE TITLE
Undocumented selectors functionality in `createSlice`

### ISSUE THREAD

**Issue by mattkahl** [reduxjs/redux-starter-kit#51]
Thanks for the great tool! It uncovers some great existing utilities, provides some new ones, and sheds light on some useful idioms.

I had a question regarding `createSlice`. Having used a "ducks" structure previously, this was a great thing to uncover. And, naturally, I wondered why there wasn't an ability to also pass selectors into `createSlice`. However, I noticed that there *is* the ability to pass selectors into `createSlice` but it's undocumented. My only complaint about the functionality as it stands is that it modifies the name of selector. I understand why that happens for actions (and it makes it more readable to boot!), but I don't quite understand why that is needed for selectors.

So, two questions:
1. Are you planning on exposing this functionality in the documentation? Or is it hidden for a reason?
2. Would you be open to either (a) changing this functionality or (b) exposing `createSliceSelector` for import?

Thanks!

**Comment by mattkahl** [comment]
Thanks! Will do. 

Looking at this more closely, it's not operating exactly the way I assumed.

I'll close now and maybe/hopefully open a PR after doing some battle-testing myself on a current project.

My thinking was that some `toString` niceties would be added via `createSelector` (a lá `createAction`) and an array of selectors could be passed to `createSlice`. All of those selectors would be wrapped via a function that passes in only the slice to the selector. Then they could be accessed via `todosSlice.selectors.getCompleted(store.getState())`.

I now see that I extrapolated the current implementation into something it wasn't. Realizing that the intention would be to use the generated slice selector when invoking a specific selector `getCompleted(todosSlice.selectors.getTodos())`.

**Comment by markerikson** [comment]
Just removed the slice selectors functionality entirely in #193 , on the grounds that it was useless.  See #91 for more discussion.

**Comment by Letrab** [comment]
FYI: There is still a reference to it in the README.md:

A createSlice() function that accepts a set of reducer functions, a slice name, and an initial state value, and automatically generates corresponding action creators, types, **and simple selector functions.**

**Comment by markerikson** [comment]
Thanks, fixed.
