### ISSUE TITLE
Remote Redux Devtools / React Native Debugging Support?

### ISSUE THREAD

**Issue by justinkwanlee** [reduxjs/redux-starter-kit#66]
Are the devtools supported when using this library with react-native?

If no, is it possible to support [remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools) which would allow devtools on react-native projects

**Comment by denisw** [comment]
You should be able to achieve basic `remote-redux-devtools` integration by setting `devTools` to `false` and instead passing `devToolsEnhancer` using the `enhancers` option:

```js
import { configureStore } from 'redux-starter-kit'
import devToolsEnhancer from 'remote-redux-devtools'

// ...

const store = configureStore({
  reducer,
  devTools: false,
  enhancers: [devToolsEnhancer]
})
```

This mostly works, but ["actions dispatched from Redux DevTools will not flow to your middlewares"](https://github.com/zalmoxisus/remote-redux-devtools#when-to-use-devtools-compose-helper). This is something that can only be fixed within redux-starter-kit by wrapping all store enhancers in redux-remote-devtools' `composeWithDevTools`, which is what `devTools: true` does for the "local" devtools extension.

@markerikson Do you think it makes sense to extend the `devTools` option to accept an additional `'remote'` value (and perhaps, for symmetry, a value `'local'` that is an alias for the current`true`)?

**Comment by PierreCapo** [comment]
@denisw I've tried your solution and it's not working for me :(

**Comment by markerikson** [comment]
I believe this was resolved by #130 .

**Comment by dkthehuman** [comment]
I believe the point in https://github.com/reduxjs/redux-toolkit/issues/66#issuecomment-452815462 about needing to wrap all store enhancers with the `composeWithDevTools` from `remote-redux-devtools` in order to dispatch actions to middleware still holds. AFAICT, #130 only supports `composeWithDevTools` from `redux-devtools-extension`, which doesn't support remote connections.

@markerikson What do you think about @denisw's proposal to extend the `devTools` option?

**Comment by phryneas** [comment]
This would probably introduce a dependency to `remote-redux-devtools` that would be problematic to tree-shake and add sub-dependencies to `lodash`, `socketcluster-client` and others, bringing RTK from ~12kb gzipped up to ~40kb gzipped.

So, adding a reference like that is pretty much out of the question :disappointed:

**Comment by markerikson** [comment]
The only actual limiting factor here is whether hand-dispatching actions via the DevTools UI actually hits middleware, right?  That seems like a _very_ niche use case.

**Comment by dkthehuman** [comment]
Ah, I think you're right. I'm setting up Redux DevTools for the first time and thought that not being able to wrap the store enhancers might have more of a negative impact on its functionality, but it looks like it's not that big of a deal. Thanks @phryneas and @markerikson!

**Comment by RajeevPrakashAD1** [comment]
I am using redux toolkit in my re

act native project and its not getting connected to debugger it showing error  websocket connection to.....
<img width="416" alt="Screenshot 2021-12-01 194854" src="https://user-images.githubusercontent.com/80143190/144250709-4c5c6933-ffd3-48be-80be-f24a48cb6e3d.png">
