### ISSUE TITLE
actionCreator#toString didn't work on switch case

### ISSUE THREAD

**Issue by agusputra** [reduxjs/redux-starter-kit#72]
It seems action creator cannot be used inside switch case. `case action1` didn't call toString() 

Sample code:

```
import { createAction } from "redux-starter-kit"

const action1 = createAction("action1")
const theAction = action1()

switch (theAction.type) {
  case action1:
    console.log(theAction.type)
    break
  default:
    console.log('DEFAULT')
}

// Output: DEFAULT
```

**Comment by denisw** [comment]
Unfortunately, JavaScript's semantics don't allow customizing how the `case` matching is done; it's always as if comparing with `===`. Your only option is to call `toString()` directly:

```js
switch (theAction.type) {
  case action1.toString():
    console.log(theAction.type)
    break
  default:
    console.log('DEFAULT')
}
```

A possible readability improvement could be to let `createAction()` set not only `toString()`, but also a `type` attribute on the action creator function. Then the above could be written as:

```js
switch (theAction.type) {
  case action1.type:
    console.log(theAction.type)
    break
  default:
    console.log('DEFAULT')
}
```

**Comment by denisw** [comment]
@markerikson Another benefit of adding a `type` field to `createAction()` action creators would be slightly better support for non-string action types - specifically, being able to retrieve them from the action creator in their non-string-converted form. Arguably, this is an edge case though, `redux-starter-kit` being opinionated towards string action types and all.

**Comment by agusputra** [comment]
> Unfortunately, JavaScript's semantics don't allow customizing how the `case` matching is done; it's always as if comparing with `===`. Your only option is to call `toString()` directly:
> 
> ```js
> switch (theAction.type) {
>   case action1.toString():
>     console.log(theAction.type)
>     break
>   default:
>     console.log('DEFAULT')
> }
> ```
> 
> A possible readability improvement could be to let `createAction()` set not only `toString()`, but also a `type` attribute on the action creator function. Then the above could be written as:
> 
> ```js
> switch (theAction.type) {
>   case action1.type:
>     console.log(theAction.type)
>     break
>   default:
>     console.log('DEFAULT')
> }
> ```

Yeah it's because I see the example here: https://github.com/reduxjs/redux-starter-kit/commit/6da70cba1d51088664965ff60d1071148b029dd7#diff-5f580528e66e02eecffa3be1b7314c3aR31

I think you should update the example or add `createAction()#type`

**Comment by markerikson** [comment]
@agusputra : hmm.  yeah, that one may be my fault for writing a bad example.

**Comment by neurosnap** [comment]
Another solution:

```js
switch (theAction.type) {
  case `${action1}`:
    console.log(theAction.type)
    break
  default:
    console.log('DEFAULT')
}
```

**Comment by markerikson** [comment]
Action creators now have a `.type` field, and the docs have been updated.  Sorry for the confusion!

**Comment by ZivGit** [comment]
> 动作创建者现在有一个`.type`字段，并且文档已更新。对困惑感到抱歉！

Seems like there is still a problem with the endpoint ;-(
```
postApi.endpoints.getPostsByUserId.matchFulfilled.type // undefined
postApi.endpoints.getPostsByUserId.matchFulfilled // [Function anonymous], not [Function actionCreator]
```

**Comment by phryneas** [comment]
@ZivGit  

Those are matcher functions, not action creators. You **have** to use the `extraReducers` builder notation, **with `addMatcher`, not `addCase`** to use those. By the way, we will be deprecating the `extraReducers` object notation and you should switch away from that in general. (see https://github.com/reduxjs/redux-toolkit/issues/2301)

**Comment by ZivGit** [comment]
@phryneas 
thank you for the explanation.
But I don't seem to have a choice, the reason is that my project is using redux-ORM, meaning I won't be able to use `addMatcher` `addCase`
[https://redux-orm.github.io/redux-orm/advanced/custom-reducer](https://redux-orm.github.io/redux-orm/advanced/custom-reducer)
