### ISSUE TITLE
[ts-next] Index.d.ts incorrectly imports from 'src'

### ISSUE THREAD

**Issue by SKCrawford** [reduxjs/redux-starter-kit#80]
The index.d.ts attempts to import from src/, leading to broken exports. [Referencing this comment on the corresponding pull request.](https://github.com/reduxjs/redux-starter-kit/pull/73#issuecomment-454316929) Thanks for your hard work on implementing TypeScript support.

**Comment by markerikson** [comment]
Paging @denisw ...

**Comment by denisw** [comment]
I just pushed a change to #73 that uses `tsc -d` to generate TypeScript declaration files from our source files and writes them to `./dist`. `index.d.ts` now points to these `dist/` files.

**Comment by nickmccurdy** [comment]
FYI I think it's easier to generate declaration files with rollup-plugin-typescript(2)

**Comment by denisw** [comment]
@nickmccurdy Thanks for the hint. I assumed so far things would be easier by using the Babel TypeScript transform for the build rather than the TypeScript compiler _and_ Babel (for instance, Jest just works without plugins), but with the added declaration file requirement we might need to reconsider.

**Comment by nickmccurdy** [comment]
Didn't realized it was babel based, I guess using tsc is easier. But you can probably still automate running that from rollup or another build tool. And yea I meant 2.

**Comment by SKCrawford** [comment]
TSServer is now correctly inferring types, so I'm going to go ahead and close this. Thanks for getting it figured out.
