### ISSUE TITLE
Slices inside slices

### ISSUE THREAD

**Issue by lkuoch** [reduxjs/redux-starter-kit#89]
Hi all,

I'm not sure if this has been asked before but would it be possible to have `createSlice` reference other maybe an array/collection of other slices.

I'm quite new to redux and have only ready the API docs but it seems to me that slices are a great way to condense all the redux boilerplate and provide a much better way of organising your code.

I was thinking something like this:

* You only need to create a root slice which can reference every other slice
```javascript
const rootSlice= createSlice({
    references: [slice1, slice2] // Maybe this or something similar
})
```

* Then you effectively have name spaces and only need to create one file with all your actions/reducers etc
```javascript
// slice1.js
const sliceOne = createSlice({
    // initialState, reducers etc. 
    references: [slice1a] // Refers to another slice
})
```
So in the end you can have all your redux logic isolated in their own file.

Let me know what you think,
Thanks

**Comment by markerikson** [comment]
That's an interesting idea, and not one I'd really thought about.  I just opened up #91 to discuss desired behavior for `createSlice` - let's move the discussion over there.
