### ISSUE TITLE
Feature: Slice helpers

### ISSUE THREAD

**Issue by neurosnap** [reduxjs/redux-starter-kit#92]
Slice helpers abstract the need to recreate repetitive reducers/actions, etc.  I have found myself creating a lot of the same type of reducers and by creating a thin wrapper around `createSlice` I'm reducing a ton of boilerplate code.

The primary slices I create often are `map` and simple `assign`.  I've been using these slices in production for awhile now with great success.

Here are some examples:
https://github.com/neurosnap/robodux#slice-helpers

Map slice:

```js
interface SliceState {
  [key: string]: string;
}
interface State {
  test: SliceState
}

interface Actions {
  addTest: State;
  setTest: State;
  removeTest: string[];
  resetTest: never;
}

const slice = 'test';
const { reducer, actions } = mapSlice<SliceState, Actions, State>(slice);
const state = { 3: 'three' };

store.dispatch(
  actions.addTest({
    1: 'one',
    2: 'two',
  })
);
/* {
  1: 'one',
  2: 'two',
  3: 'three,
} */

store.dispatch(
  actions.setTest({ 4: 'four', 5: 'five', 6: 'six' })
)
/* {
  4: 'four',
  5: 'five',
  6: 'six',
} */

store.dispatch(
  actions.removeTest(['5', '6'])
)
/* {
  4: 'four'
} */

store.dispatch(
  actions.resetTest()
)
// {}
```

What does everyone think?

I'd be happy to submit a PR to add this feature to RSK.

**Comment by markerikson** [comment]
Swinging back around to this.  Appreciate the suggestion, but I don't think this is something I want to add at this point.
