### ISSUE TITLE
Parameters of actions are not infered

### ISSUE THREAD

**Issue by bassplayerch** [reduxjs/redux-starter-kit#93]
After trying out your hello world example I noticed, that the parameters of the actions are not infered.
Here's what I got:

```typescript
export const counter = createSlice({
	slice: 'counter', 
	initialState: 0,
	reducers: {
		increment: (state) => state + 1,
		decrement: (state) => state - 1,
		multiply: (state, action: PayloadAction<number>) => state * action.payload
	}
});

counter.actions.multiply() // should error out
counter.actions.multiply("2") // should error out

```
The call to counter.actions.multiply without any or the wrong arguments shouldn't be possible since it will generate a runtime error. Is this intended behaviour or am I doing something wrong / it's not possible?

**Comment by markerikson** [comment]
I sorta noticed this myself, but I don't know enough about the TS behavior to say anything.

Paging @denisw , @Dudeonyx , and @jessidhia ...

**Comment by denisw** [comment]
This problem is inherited from how `createAction` is typed. If you write `createAction('foo')`, we don't really know if you intended actions with or without payload, so I typed `PayloadActionCreator` to accept being called either without or with payload argument.

I used this `PayloadActionCreator` for `createSlice` as well, but maybe we can do better here. I can experiment.

**Comment by denisw** [comment]
Sorry, I misremembered. We are currently _not_ using the `PayloadActionCreator` type, but `ActionCreator<T>`, which is typed as `(...args: any[]) => T`. I'll try to make things more precise.

**Comment by bassplayerch** [comment]
> @bassplayerch I created a PR (#94) that should fix the issue. It would be great if you could test whether it works for you.

Works perfectly for me. I also tested it wîth an object and array of objects.
Thanks a lot!
 I found another small issue but since I don't think this is related I'll open a new issue.
