### ISSUE TITLE
should createAction be able to accept a payloadCreator function as a second argument?

### ISSUE THREAD

**Issue by aholachek** [reduxjs/redux-starter-kit#95]
In the redux-actions library's [version of `createAction`](https://redux-actions.js.org/api/createaction#createactiontype-payloadcreator), you can provide an optional second argument, a `payloadCreator` function. In the past, I've used it for things like generating a unique id for a new item before passing it along. (I don't know if that is best practice though). 

Is adding the `payloadCreator` argument  to your version of `createAction` something you would consider?

**Comment by aholachek** [comment]
Ah, got it, thanks (I didn't look very hard for previous issues about this). I'll close this. Thanks very much for making this library, it's going to be so nice to have a centralized place for these useful patterns.

**Comment by markerikson** [comment]
Sure.  Yeah, there's dozens (hundreds?) of similar libs out there already, but the goals are are to have one that's "official", and also integrates some other niceties.

Tell you what, leave a comment over in #91 regarding this.
